server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hejxtom/microservicecloud-config.git
#          search-paths: config-repo
          username: hejxtom@163.com   #账号密码写真实的快一些我觉得，不使用也能访问有点慢
          password: sjq201314  #密码